### ISSUE TITLE
No :Terraform command

### ISSUE THREAD

**Issue by Zman94** [hashivim/vim-terraform#111]
Hello. Continuation of #82 because that issue is stale. I'm also running through the solution there, it looks like the commit placed as a solution to that issue isn't working for me. I already have the line `autocmd! filetypedetect BufRead,BufNewFile *.tf` in my `ftdetect/terraform.vim` file. Extra information, I'm using `VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 05:28:49)` and an old version of terraform `Terraform v0.11.13`. No terraform files show up in `:scriptnames`. Any thoughts?

**Comment by dimbleby** [comment]
> No terraform files show up in :scriptnames. Any thoughts?

Nope.

Directory layout etc for this plugin is, so far as I know, completely standard.  And it works for lots of other people.  So my prior is fairly strongly weighted towards: there's something unusual about your setup, rather than there being a problem with this plugin.

(Not ruling that out!  Just saying what I think is most likely).

If you do make progress figuring this out - even if it's not a problem with the plugin - please update here so that future people can benefit.

**Comment by Zman94** [comment]
So I'm not sure what the issue was. However, I did move the plugin location from the bottom of my plugin list to just below Vundle.vim and I am no longer getting the issue. I'm going to close this issue for now, but if it does come up again, I have saved my current scriptnames and I will reopen it with a diff of the working scriptnames and the bugged scriptnames command. Thanks!

**Comment by pgporada** [comment]
Thanks for the report @Zman94
