### ISSUE TITLE
Allow definiting path to terraform executable

### ISSUE THREAD

**Issue by DavidGamba** [hashivim/vim-terraform#131]
I am working on different projects that have different Terraform versions. 
Each project's bootstrap has the terraform version it supports.

It would be awesome if I could define the terraform binary location per project.

**Comment by dimbleby** [comment]
> Each project's bootstrap has the terraform version it supports.

I don't know what you mean by this.

Anyway, this plugin currently works simply by finding terraform in the path.  Some options that come to mind:

- perhaps you are currently doing something so that you can run the appropriate terraform when you're not in vim?  Eg you're setting your path appropriately, or fiddling with symlinks?  
  - in that case, do that and restart vim
- if you have some means of recognizing which terraform you want from within vim, then write an autocommand which goes and does that manipulation

This is not function that I am motivated to add to this plugin; on the whole I'm more in favour of slimming the repository down than making it more complicated.

However if we can come up with something sufficiently simple that would make life easier for you - then I'd be open to a pull request, if you'd like to contribute.  Eg perhaps a variable containing the location of terraform, defaulting to just `terraform`, which you could then manipulate.

**Comment by dimbleby** [comment]
Closing as stale.

Still happy to consider a contribution along the lines outlined above.
