### ISSUE TITLE
Syntax highlighting disabled when installing "with Vim 8 packages".

### ISSUE THREAD

**Issue by istvanfedak** [hashivim/vim-terraform#143]
Syntax highlighting doesn't work when opening a *.tf file after installing the package "with Vim 8 packages"

Steps to reproduce:
1. Run the following command in the terminal:
        $ git clone https://github.com/hashivim/vim-terraform.git ~/.vim/pack/plugins/start/vim-terraform

2. Open a *.tf file

The syntax in the file wont be highlighted.

Thanks

**Comment by dimbleby** [comment]
This plugin is arranged in a very standard way, and works for lots of people.  My first guess would be that you have misunderstood something about how to install Vim 8 packages, rather than there being a problem in this repository.

I don't use Vim 8 packages myself, but I expect that `:help packages` can help.

Please update here when you figure it out - even if this is not a problem with `vim-terraform`, maybe the next person will appreciate knowing what happened!

**Comment by istvanfedak** [comment]
I was able to fix the issue by turning syntax highlighting on. 

I added syntax on to my ~/.vimrc

Thanks for the help!
