### ISSUE TITLE
question about `g:terraform_align=1`

### ISSUE THREAD

**Issue by bsdlp** [hashivim/vim-terraform#46]
I'm hoping to get some guidance on `vim-terraform`'s `g:terraform_align=1`. I've set this in my vimrc:

```
" terraform
let g:terraform_align = 1
```

However, the plugin's indentation settings aren't overriding my existing tab settings (4 space tabs...) in `.tf` files. Where should I start debugging this? I haven't the slightest clue..

**Comment by pgporada** [comment]
Just making sure, but you have an up to date version of vim-hashicorp-tools or vim-terraform installed?

**Comment by bsdlp** [comment]
hey, thanks for taking the time to help me out. i have 365dfb3 of this repo checked out.

**Comment by pgporada** [comment]
Sorry for the delay, I've been at work conferences which has been awesome. 

I believe I see what's going on. `let g:terraform_align = 1` sets the indentation level to 2 when you press enter on a line inside of a provider/resource/module/etc.

Example:
```
provider "aws" {
  region = "whatever"  #### If I press enter here, the next line will automatically be indented 2 spaces below
  profile = "default" 
}
```

I think the confusion comes in because one would expect pressing tab to be overridden to 2 spaces to conform to hashicorp style.
```
provider "aws" {
  region = "whatever"
# If I press tab here, I'll be intended 4 spaces instead of being aligned to the line above
    profile = "default"
```

As a user of that flag, you expect to have your vimrc settings overridden for terraform files correct?

**Comment by pgporada** [comment]
Ah, that was the expectation the entire time. We were accidentally setting `terraform_align=0` when `terraform_remap_spacebar=0` which is a bug.
