### ISSUE TITLE
Disable folding?

### ISSUE THREAD

**Issue by dtirer** [hashivim/vim-terraform#54]
Is it possible to disable the code folding that vim-terraform introduces?

**Comment by pgporada** [comment]
It should be disabled by default. Do you have the latest version from the repo?

What happens if you force this in your `~/.vimrc` ?
```
let g:terraform_remap_spacebar=0
```

**Comment by pgporada** [comment]
I see the problem.

Turns out that you CAN'T disable this the way it's been written. Temporary solution, remove those sections. Better solution, I make folding a toggle-able option.
https://github.com/hashivim/vim-terraform/blob/9036fe7b27a1232c2aa4ace11a623b4c1e6a16a7/after/ftplugin/terraform.vim#L24-L54
